; ----------------------
; I HIGHLY RECCOMENDED USING THE CONFIGURATION TOOL (ConfigTool.exe) TO CHANGE SETTINGS
; ConfigTool.exe is located in the same folder as this file
; ----------------------

[Variables]
Style=Horizontal
font.Name=Segoe UI
font.SizeTitle=8
font.SizeOther=7
image.GreyScale=0
image.Tint=FFFFFFFF
h.Title=14
h.Other=12
h.Bar=28
h.Item=31
y.Icon=3

color.Title=FFFFFFFF
color.Highlight=EDD400FF
color.Text=FFFFFFCC
color.Dark=00000099
color.Light=00000066
color.Seperator=FFFFFF33

format.Time=locale-time
format.Date=locale-date

disks.Drive1=C:
disks.Drive2=D:
disks.Drive3=E:
disks.Drive4=F:

weather.Zip=FIXX0002
weather.Unit=C
weather.Unit2=m

mail.User=
mail.Pass=
gcal.URL=

utorrent.User=
utorrent.Pass=

feeds.URL1=http://feeds.gawker.com/gizmodo/excerpts.xml
feeds.URL2=http://twitter.com/statuses/user_timeline/115485051.rss
feeds.URL3=http://www.xkcd.com/atom.xml
feeds.URL4=http://feeds.gawker.com/lifehacker/excerpts.xml
substitute.Item=#Normal#

network.MaxUp=1048576
network.MaxDown=10485760

launcher.App1icon=..\Icons\preferences-other.png
launcher.App1path=ConfigTool.exe
launcher.App2icon=..\Icons\firefox.png
launcher.App2path=firefox.exe
launcher.App3icon=..\Icons\applications-multimedia.png
launcher.App3path=wmplayer.exe
launcher.App4icon=..\Icons\Word.png
launcher.App4path=winword.exe
launcher.App5icon=..\Icons\text.png
launcher.App5path=notepad.exe
launcher.App6icon=..\Icons\emblem-art
launcher.App6path=mspaint.exe
launcher.App7icon=..\Icons\computerjanitor.png
launcher.App7path=cleanmgr.exe
launcher.App8icon=..\Icons\question.png
launcher.App8path=
launcher.App9icon=..\Icons\question.png
launcher.App9path=
launcher.App10icon=..\Icons\question.png
launcher.App10path=
launcher.App11icon=..\Icons\question.png
launcher.App11path=
launcher.App12icon=..\Icons\question.png
launcher.App12path=
launcher.App13icon=..\Icons\question.png
launcher.App13path=
launcher.App14icon=..\Icons\question.png
launcher.App14path=
launcher.Folder1icon=..\Icons\user-home.png
launcher.Folder1path=
launcher.Folder2icon=..\Icons\folder-documents.png
launcher.Folder2path=
launcher.Folder3icon=..\Icons\folder-downloads.png
launcher.Folder3path=
launcher.Folder4icon=..\Icons\folder-music.png
launcher.Folder4path=
launcher.Folder5icon=..\Icons\folder-pictures.png
launcher.Folder5path=
launcher.Folder6icon=..\Icons\folder-videos.png
launcher.Folder6path=
launcher.Folder7icon=..\Icons\user-desktop.png
launcher.Folder7path=